format:
  line_ending: unix
  line_width: 80
  max_pargs_hwrap: 4
  tab_size: 2
markup:
  enable_markup: false
parse:
  additional_commands:
    project_options_defaults:
      kwargs:
        PREFIX: 1
        DISABLE_STATIC_ANALYSIS: '+'
        LIBS: '2+'
        MODULES: '2+'
